### ISSUE TITLE
Heroku hosting config unnecessary

### ISSUE THREAD

**Issue by dzx11** [eelcocramer/webrtc-mp3-stream#1]
Line 38-41 in server.js not necessary for local testing and will cause running server to fail locally.
//io.configure(function() {
//  io.set("transports", ["xhr-polling"]);
//  io.set("polling duration", 10);
//});

**Comment by eelcocramer** [comment]
I do not have this issue when I run the server locally. Can you send your log? What version of nodejs are you using? Can you send the output of `npm ls`?

**Comment by dzx11** [comment]
Log:
C:\webrtc-mp3-stream\server.js:38
io.configure(function() {
   ^
TypeError: undefined is not a function
    at Object.<anonymous>
(C:\Users\user\github\webrtc-mp3-stream\server.js:38:4
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm version 2.7.4

npm ls:

webrtc-server@0.1.0-SNAPSHOT C:\webrtc-mp3-stream
├─┬ node-static@0.7.7
│ ├── colors@1.1.2
│ ├── mime@1.3.4
│ └─┬ optimist@0.6.1
│   ├── minimist@0.0.10
│   └── wordwrap@0.0.3
├── node-uuid@1.4.3
└─┬ socket.io@1.3.6
  ├─┬ debug@2.1.0
  │ └── ms@0.6.2
  ├─┬ engine.io@1.5.2
  │ ├── base64id@0.1.0
  │ ├─┬ debug@1.0.3
  │ │ └── ms@0.6.2
  │ ├─┬ engine.io-parser@1.2.1
  │ │ ├── after@0.8.1
  │ │ ├── arraybuffer.slice@0.0.6
  │ │ ├── base64-arraybuffer@0.1.2
  │ │ ├── blob@0.0.2
  │ │ ├─┬ has-binary@0.1.5
  │ │ │ └── isarray@0.0.1
  │ │ └── utf8@2.0.0
  │ └─┬ ws@0.7.2
  │   ├── options@0.0.6
  │   └── ultron@1.0.2
  ├─┬ has-binary-data@0.1.3
  │ └── isarray@0.0.1
  ├─┬ socket.io-adapter@0.3.1
  │ ├─┬ debug@1.0.2
  │ │ └── ms@0.6.2
  │ ├── object-keys@1.0.1
  │ └─┬ socket.io-parser@2.2.2
  │   ├── benchmark@1.0.0
  │   ├── component-emitter@1.1.2
  │   ├── debug@0.7.4
  │   ├── isarray@0.0.1
  │   └── json3@3.2.6
  ├─┬ socket.io-client@1.3.6
  │ ├── backo2@1.0.2
  │ ├── component-bind@1.0.0
  │ ├── component-emitter@1.1.2
  │ ├── debug@0.7.4
  │ ├─┬ engine.io-client@1.5.2
  │ │ ├── component-inherit@0.0.3
  │ │ ├─┬ debug@1.0.4
  │ │ │ └── ms@0.6.2
  │ │ ├─┬ engine.io-parser@1.2.1
  │ │ │ ├── after@0.8.1
  │ │ │ ├── arraybuffer.slice@0.0.6
  │ │ │ ├── base64-arraybuffer@0.1.2
  │ │ │ ├── blob@0.0.2
  │ │ │ ├─┬ has-binary@0.1.5
  │ │ │ │ └── isarray@0.0.1
  │ │ │ └── utf8@2.0.0
  │ │ ├─┬ has-cors@1.0.3
  │ │ │ └── global@2.0.1
  │ │ ├─┬ parsejson@0.0.1
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ parseqs@0.0.2
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ parseuri@0.0.4
  │ │ │ └─┬ better-assert@1.0.2
  │ │ │   └── callsite@1.0.0
  │ │ ├─┬ ws@0.7.2
  │ │ │ ├── options@0.0.6
  │ │ │ └── ultron@1.0.2
  │ │ └── xmlhttprequest@1.5.0
  │ ├─┬ has-binary@0.1.6
  │ │ └── isarray@0.0.1
  │ ├── indexof@0.0.1
  │ ├── object-component@0.0.3
  │ ├─┬ parseuri@0.0.2
  │ │ └─┬ better-assert@1.0.2
  │ │   └── callsite@1.0.0
  │ └── to-array@0.1.3
  └─┬ socket.io-parser@2.2.4
    ├── benchmark@1.0.0
    ├── component-emitter@1.1.2
    ├── debug@0.7.4
    ├── isarray@0.0.1
    └── json3@3.2.6

**Comment by eelcocramer** [comment]
What version of nodejs are you on?

My npm version is 2.13.3 with nodejs 0.12.7. Otherwise this might be an issue that occurs on windows? I have tested this on both Linux and Mac OSX.

**Comment by dzx11** [comment]
Sorry for the super late reply. Nodejs version v0.12.2, on windows. It must
be a windows thing because I redid the install w/ latest nodejs version
4.1.0 and it still errored.

**Comment by eelcocramer** [comment]
np. Thanks for the report. I've pushed a fix where the coe is not exectued when running it on windows.
