### ISSUE TITLE
mpe streams automatically transfers a song

### ISSUE THREAD

**Issue by albilia** [eelcocramer/webrtc-mp3-stream#2]
Hello, today I installed the mp3 streams. I am very interested to work with this addons. Only in every song, the addon automatically transfers a song and does not play it to the end. I would be very grateful for assistance.

**Comment by eelcocramer** [comment]
What do you mean by 'transfers a song' and with 'not play it to the end'. Does it not play at all? What browser are you using?

**Comment by albilia** [comment]
It seems to me according to your question that I went to the wrong place :)
Are you the developer of this addon? <removed url>

**Comment by eelcocramer** [comment]
No, I guess you are in the wrong place.
